project:
  type: website
  output-dir: docs

website:
  title: "Orientações para elaboração de trabalhos acadêmicos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: textuais.qmd
        text: Elementos textuais
      - href: tcci.qmd
        text: TCC I
      - href: cronograma_20232.qmd
        text: Cronogramas
      - href: orientandos.qmd
        text: Orientandos
      - about.qmd

format:
  html:
    theme: minty
    css: styles.scss
    toc: true



