---
title: "TCC I"
---

# Elementos textuais
I - Introdução, onde é apresentado e contextualizado o tema do trabalho, problemática e problema, objetivos e justificativa da pesquisa;    
II - Referencial Teórico;    
III - Metodologia; e    
IV - Cronograma (de realização do TCC II).    
Os itens pré-textuais e póstextuais obrigatórios também deverão ser apresentados, são eles: capa, folha de rosto, lista de siglas, lista de figuras, lista de quadros, lista de tabelas, sumário e referências.

# Avaliação
Na avaliação de TCC I, 10 pontos serão distribuídos em Relatórios de Acompanhamento, Anexo III, e 90 pontos serão conferidos pela banca de qualificação do projeto de TCC. A aprovação em TCC I é condicionada à nota final mínima de 60 pontos.

# Introdução
## Apresentação do tema 
- **QUAL** o grande tema do seu trabalho? (duas páginas)

## Pergunta-problema 
- **O QUE** você quer responder com este trabalho? (meia página)

## Justificativa/relevância 
- **POR QUE** este trabalho é importante? (uma página)

## Objetivos geral e específico 
- **O QUE** você vai fazer para responder a pergunta-problema? **QUAIS** são as contribuições intermediárias do seu trabalho?(uma página)

# Revisão da literatura

O referencial teórico é um `texto estruturado`, apresentando `o que já foi publicado até o momento com relação ao seu tema de pesquisa`, mas principalmente como a `teoria entende os conceitos` que você irá investigar para responder seu problema de pesquisa.

- apresentar os principais conceitos presentes no seu `problema de pesquisa` 
- `discuti-los` seguindo uma `lógica de argumentação`
- Para isso, o referencial teórico será escrito com base em uma `revisão de literatura`.
- Foque nos conceitos e não nas publicações!!!!!!!!!!!!!

## Por que fazer?
- Arcabouço teórico
- Fundamentação conceitual
- Direcionamento - construção do método

## O que devo incluir? Como encontrar as referências?

### Seleção de `artigos`
:::: {.columns}
::: {.column width="50%"}
- `Revistas de alto impacto`  
  - JCR   
  - Qualis   
  - Citescore   
  - Google Scholar   
  - [Web of science - app mobile](https://clarivate.com/web-of-science-my-research-assistant/?utm_source=owned&utm_medium=banner&utm_campaign=My_Research_Assistant_App_Parent_SAR_Global_2021&utm_content=wos-blue-banner)   
  - Elsevier   
  - Scopus
:::

::: {.column width="50%"}
- `Perecibilidade da publicação`
- Pesquisa 
  - [Scispace](https://typeset.io)
- Snowballing 
  - [Research Rabbit](https://www.researchrabbit.ai/)
:::
::::

## O que devo incluir? Como encontrar as referências?

Defina um tempo para pesquisa de artigos !!!!!!!!!!!!!!!!!!

Você **`nunca`** vai conseguir encontrar **`TODAS`** as publicações que existem sobre o tema!

## Como construir a revisão? 

:::: {.columns}
::: {.column width="50%"}
### `Organização dos artigos`
- [Zotero](https://www.zotero.org/download/)   
- [Mendeley](https://www.mendeley.com/)

### `Elaboração de notas atômicas`
- [Notion](https://notion.so)   
- [Scrintal](https://www.scrintal.com/)   
- [Evernote](https://evernote.com)   
- [Obsidian](https://obsidian.md/)   
:::
::: {.column width="50%"}

### `Citações`
- Plugin Word - Zotero
- Plugin Chrome - Zotero

### `Revisão textual`
- [Grammarly](https://www.grammarly.com/)
- [LanguageTool](https://languagetool.org/pt-BR/wordpress?utm_source=google&utm_medium=cpc&utm_campaign=&utm_content=&utm_term=&gclid=CjwKCAjwivemBhBhEiwAJxNWN8WgXmP2-UMF9JBeOGTChhsYxndJtVnqmKsAbw3pBYU8-SoFaTZ3fxoCe_YQAvD_BwE)
:::
::::

Faça um `cronograma de leitura`!!!!!!!!!!!!!!!!!!!!!!!!!!!

**`ESCREVA, ESCREVA, ESCREVA`**, mesmo que depois o texto produzido não fique no TCC!

**`SEMPRE`** inclua a fonte pesquisada no momento da leitura/redação. Se deixar para depois, o trabalho será muito maior!

## Quais os tipos de revisão da literatura?
- Revisão narrativa ou bibliográfica
- Revisão sistemática
  - Bibliométrica
  - Meta-análise

## Atividade extra
1. Faça seu cadastro nas plataformas **`Zotero`**, **`Research Rabbit`** e **`Scispace`**
2. A partir da sua pergunta problema, escolha palavras-chave e pesquise essas palavras no Scispace e escolha dois artigos com maior número de citações e publicado em revistas de impacto. 
3. Entre na sua conta no `Research Rabbit`, crie uma coleção e adicione os DOI desses artigos para pesquisa.
4. Identifique os autores e as publicações mais relevantes nesse assunto.

